### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Seaha4487** [dolezsa/Xiaomi_Hygrothermo#4]
Have i to install this .py file sorry i am a noob because i tryed the changes with the configuration.yaml but got the error Platform not found: sensor.xiaomi_hygrothermo. how to solve this bro

**Comment by dolezsa** [comment]
hi @Seaha4487,
download by using "clone or download" and extract from zip whole 'custom_components' directory to your ha installation directory (where your configuration.yaml file is placed)... then you should update configuration.yaml like it is described in readme.

**Comment by dolezsa** [comment]
.
