### ISSUE TITLE
custom component not working in HA 0.92.0

### ISSUE THREAD

**Issue by yunnanpl** [dolezsa/Xiaomi_Hygrothermo#6]
Dear All,

it seems that the xiaomi_hygrothermo (both this from dolezsa and the original (?) from elviosebastianelli) stopped working in previous HA (due to directory rename) and now again !

Now the reason is different. It seems that the manifest.json file is missing.
When I add it, at least HA is not complaining about missing component, but still testing...

File name: manifest.json

File content maybe...:
{
  "domain": "xiaomi_hygrothermo",
  "name": "Xioami Hygrothermo",
  "documentation": "https://github.com/dolezsa/Xiaomi_Hygrothermo/blob/master/README.md",
  "dependencies": [],
  "codeowners": ["@dolezsa"],
  "requirements": []
}

EDIT: Yes, with this file added, the component is found and works as usual.
Of course great thanks to dolezsa and elviosebastianelli, for the module !

**Comment by dolezsa** [comment]
Thank you for the warning, I have added the manifest file. I am still on 0.91, so please test it and let me know, if it is ok now.

**Comment by dolezsa** [comment]
tested on 0.92.1, seems to be ok...
